apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-events
resources:
  - https://raw.githubusercontent.com/argoproj/argo-events/v1.7.6/manifests/install.yaml
  - base/namespace.yaml