##
# To Generate a UN/PW:
# `htpasswd -c auth <un>`
# PW
# PW
# `cat auth | base64`
##
---
apiVersion: v1
kind: Secret
type: Opaque
data:
  auth: YWRtaW46JGFwcjEkS1NKb0l0a3kkaUc2Nkt0RjNjeTRReVNDNHdDd0lKLwo=
metadata:
  name: basic-auth
  namespace: argocd
---
apiVersion: v1
kind: Secret
type: Opaque
data:
  auth: YWRtaW46JGFwcjEkS1NKb0l0a3kkaUc2Nkt0RjNjeTRReVNDNHdDd0lKLwo=
metadata:
  name: basic-auth
  namespace: argo
---
apiVersion: v1
kind: Secret
type: Opaque
data:
  auth: YWRtaW46JGFwcjEkS1NKb0l0a3kkaUc2Nkt0RjNjeTRReVNDNHdDd0lKLwo=
metadata:
  name: basic-auth
  namespace: argo-events
