apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/chris102994/argo-deployment.git
    targetRevision: master
    path: apps/argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Force=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-events
spec:
  project: default

  source:
    repoURL: https://github.com/chris102994/argo-deployment.git
    targetRevision: master
    path: apps/argo-events

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Force=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-rollouts
spec:
  project: default

  source:
    repoURL: https://github.com/chris102994/argo-deployment.git
    targetRevision: master
    path: apps/argo-rollouts

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Force=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
spec:
  project: default

  source:
    repoURL: https://github.com/chris102994/argo-deployment.git
    targetRevision: master
    path: apps/argo-workflows

  destination:
    server: https://kubernetes.default.svc
    namespace: argo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Force=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-load-balancer
spec:
  project: default

  source:
    repoURL: https://github.com/chris102994/argo-deployment.git
    targetRevision: master
    path: apps/metallb-load-balancer

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Force=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
spec:
  project: default

  source:
    repoURL: https://github.com/chris102994/argo-deployment.git
    targetRevision: master
    path: apps/nginx-ingress

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Force=true