apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
resources:
  - https://github.com/argoproj/argo-workflows/releases/download/v3.4.3/install.yaml
  - base/namespace.yaml
  - base/ingress.yaml
patches:
- path: base/patch-argo-server.yaml
  target:
    namespace: argo
    kind: Deployment
    name: argo-server