apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - base/namespace.yaml
  - base/ingress.yaml
  - base/application.yaml
configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: replace
    literals:
      - server.insecure=true
      - server.disable.auth=true
      - server.log.format=json
      - server.basehref=argocd